name: Build and publish API client to branch

on:
  push:
    tags:
      - v*

jobs:
  build_and_publish:
    name: Build and publish API client to branch
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master

      - name: Set env from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Version
        run: echo ${{ env.RELEASE_VERSION }}

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 15

      - run: wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.1.1/openapi-generator-cli-5.1.1.jar -O openapi-generator-cli.jar

      - name: Generate API client and contracts
        run: java -jar openapi-generator-cli.jar generate -i https://api.nephrogo.com/v1/schema.json/ -g dart-dio-next -o api --additional-properties="pubAuthor=Karolis,pubName=nephrogo_api_client,disallowAdditionalPropertiesIfNotPresent=false,useEnumExtension=false"

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: dart --version
      - run: flutter --version

      - run: flutter pub get
        working-directory: api

      - run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: api

      - name: Push generated client to branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: 'release/${{ env.RELEASE_VERSION }}'
          FOLDER: api
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Auto generated NephroLog API client"

